/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Car;
import model.CarHistory;

/**
 *
 * @author dgoda
 */
public class CreateNewUberPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUberPanel
     */
    
    private CarHistory carHistory;
    private JSplitPane splitPane;
            
     CreateNewUberPanel(JSplitPane splitPane, CarHistory carHistory) {
        initComponents();
            this.splitPane = splitPane;
        this.carHistory = carHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblColour = new javax.swing.JLabel();
        lblMaxSeats = new javax.swing.JLabel();
        lblAvailableCity = new javax.swing.JLabel();
        lblManufacturingYear = new javax.swing.JLabel();
        lblCarAvailable = new javax.swing.JLabel();
        lblMaintainenceAvailable = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModelNo = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        txtColour = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        cbAvailableYes = new javax.swing.JCheckBox();
        cbAvailableNo = new javax.swing.JCheckBox();
        cbCertificateYes = new javax.swing.JCheckBox();
        cbCertificateNo = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADD UBER");

        lblBrand.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrand.setText("Enter Car Brand");
        lblBrand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblModelNo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblModelNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelNo.setText("Enter Model Number");
        lblModelNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSerialNo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSerialNo.setText("Enter Serial Number");

        lblColour.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblColour.setText("Enter Colour ");

        lblMaxSeats.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMaxSeats.setText("Enter Maximum Seats ");

        lblAvailableCity.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblAvailableCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailableCity.setText("Enter Available City");

        lblManufacturingYear.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblManufacturingYear.setText("Enter Manufacturing Year");

        lblCarAvailable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblCarAvailable.setText("Is Car Available?");

        lblMaintainenceAvailable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMaintainenceAvailable.setText("Is Maintainance Certificate Available?");
        lblMaintainenceAvailable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        txtMaxSeats.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaxSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxSeatsActionPerformed(evt);
            }
        });

        txtManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturingYearActionPerformed(evt);
            }
        });

        cbAvailableYes.setText("YES");

        cbAvailableNo.setText("NO");

        cbCertificateYes.setText("YES");

        cbCertificateNo.setText("NO");
        cbCertificateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCertificateNoActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBrand)
                                    .addComponent(lblModelNo)
                                    .addComponent(lblSerialNo)
                                    .addComponent(lblColour)
                                    .addComponent(lblMaxSeats)
                                    .addComponent(lblAvailableCity)
                                    .addComponent(lblManufacturingYear)
                                    .addComponent(lblCarAvailable))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBrand)
                                            .addComponent(txtModelNo)
                                            .addComponent(txtSerialNo)
                                            .addComponent(txtColour)
                                            .addComponent(txtMaxSeats)
                                            .addComponent(txtAvailableCity)
                                            .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbCertificateYes)
                                            .addComponent(cbAvailableYes))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cbAvailableNo)
                                            .addComponent(cbCertificateNo))
                                        .addGap(82, 82, 82))))
                            .addComponent(lblMaintainenceAvailable)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCertificateYes)
                        .addComponent(cbCertificateNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrand)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialNo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtColour, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblColour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaxSeats)
                            .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAvailableCity)
                            .addComponent(lblAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtManufacturingYear)
                            .addComponent(lblManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarAvailable)
                            .addComponent(cbAvailableYes)
                            .addComponent(cbAvailableNo))
                        .addGap(18, 18, 18)
                        .addComponent(lblMaintainenceAvailable)))
                .addGap(81, 81, 81)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void txtMaxSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxSeatsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
         Car car = new Car();
        
        String brand = txtBrand.getText();
        if (brand == null || brand.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Enter a Brand");
        }
        else{
            car.setBrand(brand);
        }
        
        
        
        String modelNo = txtModelNo.getText();
        if (modelNo == null || modelNo.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Enter a Model Number");
        }
        else{
            car.setModel_num(modelNo);
        }
        
        
        
        String colour = txtColour.getText();
        if (colour == null || colour.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Enter a Colour");
        }
        else{
            car.setColour(colour);
        }

        
        
        String availableCity = txtManufacturingYear.getText();
        if (availableCity == null || availableCity.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Enter a City");
        }
        else{
            car.setAvailable_city(availableCity);
        }
        
        
        
        String serialNo = txtSerialNo.getText();
         try {
            Integer.parseInt(serialNo);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Enter a Serial Number");
            return;
        }
        car.setSerial_num(Integer.parseInt(serialNo));
        
        
        
         String manufactured_year = txtManufacturingYear.getText();
        try {
            Integer.parseInt(manufactured_year);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Enter Manufacturing Year.");
            return;
        }
        car.setManufactured_year(Integer.parseInt(manufactured_year));
        
        
        
        String max_seats = txtMaxSeats.getText();
        try {
            Integer.parseInt(max_seats);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Enter Maximum Seats.");
            return;
        }
        car.setMax_seats(Integer.parseInt(max_seats));
        car.setMin_seats(1);
        
        if(cbAvailableYes.isSelected() == false && cbAvailableNo.isSelected() == false)
        {
           JOptionPane.showMessageDialog(null,"Select one Option in Car Available");
           return; 
        }
        else
        {
            boolean available;
            if(cbAvailableYes.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }           
            car.setAvailable(available);
        }
        
        if(cbCertificateYes.isSelected() == false && cbCertificateYes.isSelected() == false)
        {
           JOptionPane.showMessageDialog(null,"Select Certificate Option.");
           return; 
        }
        else
        {
            boolean available;
            if(cbCertificateNo.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }           
            car.setMaintainance_certificate(available);
        }
        
        carHistory.addCar(car);
        JOptionPane.showMessageDialog(null,"Details Added Successfully");
        txtBrand.setText("");
        txtModelNo.setText("");
        txtColour.setText("");
        txtAvailableCity.setText("");
        txtSerialNo.setText("");
        txtManufacturingYear.setText("");
        txtMaxSeats.setText("");
        cbAvailableYes.setSelected(false);
        cbAvailableNo.setSelected(false);
        cbCertificateYes.setSelected(false);
        cbCertificateNo.setSelected(false);
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbCertificateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCertificateNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCertificateNoActionPerformed

    private void txtManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturingYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbAvailableNo;
    private javax.swing.JCheckBox cbAvailableYes;
    private javax.swing.JCheckBox cbCertificateNo;
    private javax.swing.JCheckBox cbCertificateYes;
    private javax.swing.JLabel lblAvailableCity;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarAvailable;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblMaintainenceAvailable;
    private javax.swing.JLabel lblManufacturingYear;
    private javax.swing.JLabel lblMaxSeats;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
