/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Car;
import model.CarHistory;

/**
 *
 * @author dgoda
 */
public class SearchUberRidesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchUberRidesPanel
     */
    
    private CarHistory carHistory;
    private JSplitPane splitPane;
    public SearchUberRidesPanel(JSplitPane splitPane, CarHistory carHistory) {
        initComponents();
        this.carHistory = carHistory;
        this.splitPane = splitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvailability = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnMaintainance = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnManufacturers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblManufacturingYear = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        txtSearchBrand = new javax.swing.JTextField();
        txtSearchManufacturing = new javax.swing.JTextField();
        txtSearchSerial = new javax.swing.JTextField();
        txtSearchModel = new javax.swing.JTextField();
        boxSearchCity = new javax.swing.JComboBox<>();
        boxSearchMin = new javax.swing.JComboBox<>();
        lblBrand6 = new javax.swing.JLabel();
        boxSearchMax = new javax.swing.JComboBox<>();
        lblBrand7 = new javax.swing.JLabel();
        btnSearchBrand = new javax.swing.JButton();
        btnSearchManufacturingYear = new javax.swing.JButton();
        btnSearchSerialNo = new javax.swing.JButton();
        btnSearchModelNo = new javax.swing.JButton();
        btnSearchCity = new javax.swing.JButton();
        btnSearchSeats = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILTER UBER RIDES");

        btnAvailability.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnAvailability.setText("Number of Cars Currently Available");
        btnAvailability.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilityActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnDisplay.setText("Display First Available Car");
        btnDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnMaintainance.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnMaintainance.setText("Cars with expired Maintanence Certificate");
        btnMaintainance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaintainance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintainanceActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnUpdate.setText("Last time fleet was Updated");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnManufacturers.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnManufacturers.setText("Manufacturers Used by this Uber");
        btnManufacturers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturersActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEARCH UBER RIDES");

        lblBrand.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblBrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrand.setText("Search by Brand");
        lblBrand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblManufacturingYear.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblManufacturingYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturingYear.setText("Search by Manufacturing Year");
        lblManufacturingYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSerialNo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSerialNo.setText("Search by Serial Number");
        lblSerialNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblModelNo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblModelNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelNo.setText("Search by Model Number");
        lblModelNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCity.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("Search by City");
        lblCity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSeats.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeats.setText("Search Cars with Min & Max Seats");
        lblSeats.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtSearchManufacturing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchManufacturingActionPerformed(evt);
            }
        });

        txtSearchSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSerialActionPerformed(evt);
            }
        });

        txtSearchModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchModelActionPerformed(evt);
            }
        });

        boxSearchCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York", "San Jose", "Chicago", "Ohio", "Seattle", "Austin" }));
        boxSearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSearchCityActionPerformed(evt);
            }
        });

        boxSearchMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        lblBrand6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblBrand6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrand6.setText("Min Seats");
        lblBrand6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        boxSearchMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        lblBrand7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblBrand7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrand7.setText("Max Seats");
        lblBrand7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSearchBrand.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchBrand.setText("Search");
        btnSearchBrand.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBrandActionPerformed(evt);
            }
        });

        btnSearchManufacturingYear.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchManufacturingYear.setText("Search");
        btnSearchManufacturingYear.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManufacturingYearActionPerformed(evt);
            }
        });

        btnSearchSerialNo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchSerialNo.setText("Search");
        btnSearchSerialNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSerialNoActionPerformed(evt);
            }
        });

        btnSearchModelNo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchModelNo.setText("Search");
        btnSearchModelNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelNoActionPerformed(evt);
            }
        });

        btnSearchCity.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchCity.setText("Search");
        btnSearchCity.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCityActionPerformed(evt);
            }
        });

        btnSearchSeats.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSearchSeats.setText("Search");
        btnSearchSeats.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.white));
        btnSearchSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(233, 233, 233))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMaintainance, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(107, 107, 107)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManufacturingYear)
                                    .addComponent(lblSerialNo)
                                    .addComponent(lblModelNo)
                                    .addComponent(lblBrand)
                                    .addComponent(lblCity))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSearchSerial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchManufacturing, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchBrand, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchModel)
                                    .addComponent(boxSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeats)
                                .addGap(18, 18, 18)
                                .addComponent(boxSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBrand6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBrand7)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaintainance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtSearchBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturingYear)
                    .addComponent(txtSearchManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSearchSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNo)
                    .addComponent(txtSearchModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(btnSearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(boxSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand6)
                    .addComponent(boxSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand7)
                    .addComponent(btnSearchSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilityActionPerformed
        // TODO add your handling code here:
        int available = carHistory.availableCar();
        int notAvailable = carHistory.getCarList().size() - available;
        JOptionPane.showMessageDialog(null,"\nNumber of cars Available: "+ available+"\n\nNumber of cars not Available:"+notAvailable);
    }//GEN-LAST:event_btnAvailabilityActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
       ArrayList<Car> list = new ArrayList<Car>();
        list.add(carHistory.firstAvailable());
        CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Cars Available");
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnMaintainanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintainanceActionPerformed
        // TODO add your handling code here:
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchByMaintenanceCertificate();
         CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"None Cars with Maintenance Certificate found");
        }
    }//GEN-LAST:event_btnMaintainanceActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         Date fleet = new Date();
        fleet = carHistory.lastUpdated();
        JOptionPane.showMessageDialog(null,"Last time fleet was Updated on "+ fleet);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturersActionPerformed
        // TODO add your handling code here:
        
         String list = carHistory.carManufactures();
        JOptionPane.showMessageDialog(null,"Manufacturers used by Uber are:\n" + list);
        
    }//GEN-LAST:event_btnManufacturersActionPerformed

    private void txtSearchSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSerialActionPerformed

    private void txtSearchModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchModelActionPerformed

    private void txtSearchManufacturingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchManufacturingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchManufacturingActionPerformed

    private void btnSearchBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBrandActionPerformed
        // TODO add your handling code here:
         String brand = txtSearchBrand.getText();
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchByBrand(brand);
        CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        txtSearchBrand.setText("");
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Cars of the Brand found");
            txtSearchBrand.setText("");
        }
    }//GEN-LAST:event_btnSearchBrandActionPerformed

    private void btnSearchManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManufacturingYearActionPerformed
        // TODO add your handling code here:
           String ye = txtSearchManufacturing.getText();
        try {
            Integer.parseInt(ye);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Year is not a valid.");
            return;
        }
        int year = Integer.parseInt(ye);
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchByYear(year);
        txtSearchManufacturing.setText("");
        CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent( panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Cars of the year found");
            txtSearchManufacturing.setText("");
        }
    }//GEN-LAST:event_btnSearchManufacturingYearActionPerformed

    private void btnSearchSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSerialNoActionPerformed
        // TODO add your handling code here:
           String serial = txtSearchSerial.getText();
        try {
            Integer.parseInt(serial);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Serial Number is not a valid number.");
            return;
        }
        int serial_num = Integer.parseInt(serial);
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchBySerialNumber(serial_num);
         CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        txtSearchSerial.setText("");
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Cars of the Serial Number found");
            txtSearchSerial.setText("");
        }
    }//GEN-LAST:event_btnSearchSerialNoActionPerformed

    private void btnSearchModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelNoActionPerformed
        // TODO add your handling code here:
           String model_num = txtSearchModel.getText();
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchByModelNumber(model_num);
        CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        txtSearchModel.setText("");
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Cars of the Model found");
            txtSearchModel.setText("");
        }
    }//GEN-LAST:event_btnSearchModelNoActionPerformed

    private void btnSearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCityActionPerformed
        // TODO add your handling code here:
         String city = boxSearchCity.getSelectedItem().toString();
        ArrayList<Car> list = new ArrayList<Car>();
        list = carHistory.searchByAvailableInCity(city);
        CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent(panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"None Cars availsble in the Selected City");
        }
    }//GEN-LAST:event_btnSearchCityActionPerformed

    private void btnSearchSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSeatsActionPerformed
        // TODO add your handling code here:
      int min = Integer.parseInt(boxSearchMin.getSelectedItem().toString());
        int max = Integer.parseInt(boxSearchMax.getSelectedItem().toString());
        ArrayList<Car> list = new ArrayList<Car>();
       
        list = carHistory.searchBySeats(min, max);
         CarHistory brandFilterCar = new CarHistory();
        brandFilterCar.setCarList(list);
        if(list.size() > 0){
            ViewUberRides panel = new ViewUberRides(splitPane, brandFilterCar);
            splitPane.setRightComponent( panel);
//            CardLayout layout = (CardLayout)splitPane.getLayout();
//            layout.next(splitPane);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"None Cars with such Seating arrangment");
        }
    }//GEN-LAST:event_btnSearchSeatsActionPerformed

    private void boxSearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSearchCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSearchCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSearchCity;
    private javax.swing.JComboBox<String> boxSearchMax;
    private javax.swing.JComboBox<String> boxSearchMin;
    private javax.swing.JButton btnAvailability;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnMaintainance;
    private javax.swing.JButton btnManufacturers;
    private javax.swing.JButton btnSearchBrand;
    private javax.swing.JButton btnSearchCity;
    private javax.swing.JButton btnSearchManufacturingYear;
    private javax.swing.JButton btnSearchModelNo;
    private javax.swing.JButton btnSearchSeats;
    private javax.swing.JButton btnSearchSerialNo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrand6;
    private javax.swing.JLabel lblBrand7;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturingYear;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JTextField txtSearchBrand;
    private javax.swing.JTextField txtSearchManufacturing;
    private javax.swing.JTextField txtSearchModel;
    private javax.swing.JTextField txtSearchSerial;
    // End of variables declaration//GEN-END:variables
}
